version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    container_name: go-backend-db
    ports:
      - "5454:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=supersecret
      - POSTGRES_USER=userAdmin
      - POSTGRES_DB=postgres_challenge
    networks:
      - network
    restart: always

networks:
  network:
    name: "backend-network"

volumes:
  postgres_data:
    name: "go-backend-db-data"
