services:
  api:
    build:
      context: .
      args:
        - PORT=:8080
    ports:
      - 3000:8080
    environment:
      - PORT=:8080
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/${POSTGRES_DB}
      - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
    restart: on-failure
    depends_on:
      - postgres
  postgres:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5446:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

volumes:
  postgres_data:
    name: "go-backend-db-data"