services:
  api:
    build:
      context: .
    ports:
      - 3333:8080
    environment:
      - DATABASE_URL=postgres://userAdmin:supersecret@localhost:5656/postgres_challenge
    restart: on-failure
    depends_on:
      - db
  db:
    image: postgres:14-alpine
    volumes:
      - ./db_data:/var/lib/postgresql/data
    ports:
      - 5656:5432
    environment:
      - DATABASE_URL=postgres://userAdmin:supersecret@localhost:5656/postgres_challenge
      - POSTGRES_USER=userAdmin
      - POSTGRES_PASSWORD=supersecret
      - POSTGRES_DB=postgres_challenge